apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-feed
  template:
    metadata:
      labels:
        app: api-feed
    spec:
      containers:
        - name: api-feed
          image: pazetox/udacity-microservices:api-feed
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USERNAME
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "99277032"
            - name: POSTGRES_HOST
              value: "database-udacity-lab.clrjhrrjum3x.us-east-1.rds.amazonaws.com"
            - name: POSTGRES_DB
              value: "postgres"
            - name: AWS_BUCKET
              value: "bucket-udacity-lab"
            - name: AWS_REGION
              value: "us-east-1"
            - name: JWT_SECRET
              value: "testing"
